template='Kewl'

[background]
primary = "#85FFBD"
secondary = "#FFFB7D"
header_font_colour = "#fff"
footer_font_colour = "#fff"
selection_bg_colour = "#A7ED9A"

[theme]
font_colour = "#fff"
selection_font_colour = "#000"
label_colour = "#fff"