template='kewl'

[background]
primary = "#85FFBD"
secondary = "#FFFB7D"
menu_box_bg_colour="#fff"
selection_bg_colour = "#A7ED9A"

[theme]
font_colour = "#fff"
selection_font_colour = "#000"
label_colour = "#fff"