template='Nico'

[background]
primary = "#2A91DB"
secondary = "#470B6C"
header_font_colour = "#000"
footer_font_colour = "#000"
selection_bg_colour = "#4441EC"

[theme]
font_colour = "#000"
selection_font_colour = "#FFF"
label_colour = "#FFF"

[extra]
menubox=['#8482CA']
header_text_gradient=['#2A8BA9','#5D2FA8']