[background]
primary="#806CFB"
secondary="#3A7385"
selection_bg_colour = "#D4B5FB"

[extra]
[extra.polygon]
colours=["#A68AD2","#79B6C3"]

[extra.ellipse]
colours=["#46CDF8","#825EE9"]

[extra.circle]
colours=["#7D32F9","#4D8EF0"]

[extra.triangle]
bgcolour="#5DDDF9"

[theme]
font_colour = "#000"
selection_font_colour = "#d0c4f5"
label_colour = "#d0c4f5"