[background]
primary="#806CFB"
secondary="#3A7385"
selection_bg_colour = "#D4B5FB"

[extra]
[extra.polygon]
primary="#A68AD2"
secondary="#79B6C3"

[extra.ellipse]
primary="#46CDF8"
secondary="#825EE9"

[extra.circle]
primary="#7D32F9"
secondary="#4D8EF0"

[extra.triangle]
bgcolor="#5DDDF9"

[theme]
font_colour = "#000"
selection_font_colour = "#d0c4f5"
label_colour = "#d0c4f5"