template='kewl'

[background]
primary = "#0093E9"
secondary = "#80D0C7"
menu_box_bg_colour="#fff"
selection_bg_colour = "#61BAEA"

[theme]
font_colour = "#fff"
selection_font_colour = "#000"
label_colour = "#fff"