template='Kewl'

[background]
primary = "#842304"
secondary = "#A59508"
header_font_colour = "#fff"
footer_font_colour = "#fff"
selection_bg_colour = "#E64B19"

[theme]
font_colour = "#fff"
selection_font_colour = "#000"
label_colour = "#fff"